app = "palmsfrontend"
primary_region = "yyz"

[build]
  [build.args]
    VITE_BACKEND_URL = "https://api.palmsbeautystore.com"

[env]
  VITE_BACKEND_URL = "https://api.palmsbeautystore.com"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256